### ISSUE TITLE
Sandbox iyzico payment 

### ISSUE THREAD

**Issue by YigitEkin** [YigitEkin/Vybe#101]
frontendde form entegrasyonu için frontend ve backend beraber koordine olmalı. Logic ikisinin aynı anda çalışmasını gerektiriyor. Bir ara bunu konuşmak için görüşme ayarlayalım. @cansrv @OguzAtaCal @canonal7 @berkturkcapar

**Comment by canonal7** [comment]
iyzico kullanilmayacak yeni issueyu takip edebilirsiniz
