### ISSUE TITLE
WP-Profile Page

### ISSUE THREAD

**Issue by canonal7** [YigitEkin/Vybe#118]
Maybe pro version can be purchased (69$)

https://tr.surveymonkey.com/r/SQ57GJC

@canonal7 @cansrv @YigitEkin @OguzAtaCal @berkturkcapar 
anketi cevaplarsaniz sevinirim

**Comment by canonal7** [comment]
Results:
https://tr.surveymonkey.com/r/SQ57GJC

**Comment by YigitEkin** [comment]
Bence daha 3 haftamız olduğu için daha ucuz alternatiflerle alakalı daha detaylı bi analiz gerçekleştirilebilir. Eğer uygun sonuç bulamazsak almak daha mantıklı bence.
