### ISSUE TITLE
Final UI Fixes for mobile

### ISSUE THREAD

**Issue by canonal7** [YigitEkin/Vybe#143]
Mobile:
- [x] Default PP
- [x] map venue pp
- [x] Comment profile picture kaldırma?
- [x] Android build?

Website:
- [x] Change profile picture
- [x] percentage?
- [x] change playlist?

**Comment by canonal7** [comment]
@YigitEkin senden bakmistik eksikler varsa ekler misin

**Comment by YigitEkin** [comment]
> @YigitEkin senden bakmistik eksikler varsa ekler misin
> 
> 

@canonal7 benim notlardakileri ekledim ancak hengilerini tamamladınız bilmiyorum ona göre tekrar bakabilir misin?
